### ISSUE TITLE
Both repo clone and downloaded zip are corrupt

### ISSUE THREAD

**Issue by amonroejj** [MapleScotDevelopment/SheepPens#1]
As of 2020-04-28, both repo clone and downloaded zip are corrupt (I tried both methods). After extract/clone, most files (like the images) are 1KB, so Godot can't read any of them.

Opening them in Notepad++ shows they're all text files in this format:
```
version https://git-lfs.github.com/spec/v1
oid sha256:eeb67acd7852ca570cbca90d3e5840834e03859238cb615a8b798e782a0d4f74
size 413924
```

**Comment by duriej** [comment]
The PNGs are uploaded with git-lfs. If you view the files in github directly you can see that they are ok.
There does seem to be an issue with github not resolving the files correctly for zip download. However the git-lfs files should work correctly with clone. Do you have git-lfs switched on on your git client?

**Comment by amonroejj** [comment]
My bad. I hadn't heard of git-lfs.
